-- Add domestic employee application and request flow.

begin;

create table if not exists public."RegistrosEmpleadasDomesticas" (
  "Id" bigint generated by default as identity primary key,
  "Nombre" text not null,
  "Email" text not null,
  "Telefono" text not null,
  "DiasDisponibles" text not null,
  "Zona" text not null,
  "Descripcion" text not null,
  "estado" text not null default 'nueva',
  "FechaEnvio" timestamptz not null default now()
);

create table if not exists public."SolicitudesEmpleadaDomestica" (
  "Id" bigint generated by default as identity primary key,
  "Nombre" text not null,
  "Email" text not null,
  "Telefono" text not null,
  "Zona" text not null,
  "Domicilio" text not null,
  "DescripcionTareas" text not null,
  "estado" text not null default 'nueva',
  "FechaEnvio" timestamptz not null default now()
);

create index if not exists idx_registros_domesticas_fecha_envio on public."RegistrosEmpleadasDomesticas" ("FechaEnvio" desc);
create index if not exists idx_registros_domesticas_estado on public."RegistrosEmpleadasDomesticas" ("estado");
create index if not exists idx_solicitudes_domesticas_fecha_envio on public."SolicitudesEmpleadaDomestica" ("FechaEnvio" desc);
create index if not exists idx_solicitudes_domesticas_estado on public."SolicitudesEmpleadaDomestica" ("estado");

alter table public."RegistrosEmpleadasDomesticas" enable row level security;
alter table public."SolicitudesEmpleadaDomestica" enable row level security;

drop policy if exists "anon_insert_empleadas_domesticas" on public."RegistrosEmpleadasDomesticas";
create policy "anon_insert_empleadas_domesticas"
on public."RegistrosEmpleadasDomesticas"
for insert
to anon
with check (true);

drop policy if exists "anon_insert_solicitudes_empleada_domestica" on public."SolicitudesEmpleadaDomestica";
create policy "anon_insert_solicitudes_empleada_domestica"
on public."SolicitudesEmpleadaDomestica"
for insert
to anon
with check (true);

drop policy if exists "admin_select_empleadas_domesticas" on public."RegistrosEmpleadasDomesticas";
create policy "admin_select_empleadas_domesticas"
on public."RegistrosEmpleadasDomesticas"
for select
to authenticated
using (public.is_admin_user());

drop policy if exists "admin_update_empleadas_domesticas" on public."RegistrosEmpleadasDomesticas";
create policy "admin_update_empleadas_domesticas"
on public."RegistrosEmpleadasDomesticas"
for update
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "admin_delete_empleadas_domesticas" on public."RegistrosEmpleadasDomesticas";
create policy "admin_delete_empleadas_domesticas"
on public."RegistrosEmpleadasDomesticas"
for delete
to authenticated
using (public.is_admin_user());

drop policy if exists "admin_select_solicitudes_empleada_domestica" on public."SolicitudesEmpleadaDomestica";
create policy "admin_select_solicitudes_empleada_domestica"
on public."SolicitudesEmpleadaDomestica"
for select
to authenticated
using (public.is_admin_user());

drop policy if exists "admin_update_solicitudes_empleada_domestica" on public."SolicitudesEmpleadaDomestica";
create policy "admin_update_solicitudes_empleada_domestica"
on public."SolicitudesEmpleadaDomestica"
for update
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "admin_delete_solicitudes_empleada_domestica" on public."SolicitudesEmpleadaDomestica";
create policy "admin_delete_solicitudes_empleada_domestica"
on public."SolicitudesEmpleadaDomestica"
for delete
to authenticated
using (public.is_admin_user());

commit;
